In [1]:
import pandas as pd
import os

In [2]:
method = 'aicso2'
g_instruments = 'ims'
task_id = '200037'

In [3]:
temp1 = os.path.join(os.path.join('temp', "{}".format(method), task_id))

In [4]:
results = pd.read_feather(
    os.path.join(temp1, "fitness.feather")).sort_values(
        by=['train_fitness'],ascending=False)

In [5]:
th = 1.1
results[(results.train_fitness > th) & (results.val_fitness > th) & (
    results.test_fitness > th
)]

,name,all_fitness,train_fitness,val_fitness,test_fitness,val_rate,test_rate
31,ultron_1751395662731039,1.362757,1.234584,1.326444,2.410764,0.074405,0.952693
59,ultron_1751492470196206,1.359284,1.168834,1.430722,3.150594,0.224060,1.695502
72,ultron_1751388038959442,1.265836,1.165698,1.657331,1.307494,0.421750,0.121641

In [6]:
results.sort_values(by=['train_fitness', 'val_fitness'],ascending=False).head(15)

,name,all_fitness,train_fitness,val_fitness,test_fitness,val_rate,test_rate
38,ultron_1751424956548625,1.505389,2.046053,0.120533,2.421303,0.941090,0.183402
40,ultron_1751388494892636,0.916575,1.876935,0.103748,-2.737709,0.944725,2.458606
53,ultron_1751410176637912,1.126525,1.874961,-0.669108,2.247750,1.356865,0.198825
39,ultron_1751397805025247,1.638331,1.816114,2.006924,0.128995,0.105065,0.928972
41,ultron_1751391914745352,1.044072,1.710714,1.103194,-3.830018,0.355126,3.238842
42,ultron_1751408482891238,0.973649,1.679157,-0.160302,-0.977946,1.095466,1.582403
43,ultron_1751431447109266,1.648786,1.669755,1.973928,1.020546,0.182166,0.388805
13,ultron_1751458566042650,0.279665,1.608895,-0.557670,-2.554679,1.346617,2.587847
44,ultron_1751385107413126,1.337144,1.596441,1.506720,-0.899213,0.056200,1.563261
45,ultron_1751400989826872,1.137660,1.565778,-0.449781,2.891835,1.287257,0.846900
47,ultron_1751418566571364,1.066588,1.553095,0.368024,-0.279060,0.763038,1.179680
46,ultron_1751464490938360,1.055762,1.544352,-0.477055,1.358791,1.308903,0.120155
62,ultron_1751462093016303,1.152508,1.536120,0.567208,0.761640,0.630752,0.504179
50,ultron_1751385093523596,0.837074,1.528450,0.290131,-0.968435,0.810180,1.633606
12,ultron_1751453966244232,1.290188,1.509855,0.000000,0.000000,1.000000,1.000000